swagger: "2.0"
info:
  version: "1.0.0"
  title: 미니트윗
host: "10.156.145.141:8000"
basePath: "/"
tags:
  - name: "User"
    description: "User API"
  - name: "Timeline"
    description: "Timeline API"
schemes:
  - "http"
paths:
  /user/email/send:
    post:
      produces:
        - "application/json"
      tags:
        - "User"
      summary: "이메일 인증번호 전송"
      parameters:
        - name: "email"
          in: "body"
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                example: "email@gmail.com"
      responses:
        200:
          description: "인증번호 전송 성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "인증번호 전송 성공"
              randomNumber:
                type: "number"
                example: 111111
        409:
          description: "이미 존재하는 이메일"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "이미 존재하는 이메일"
        500:
          description: "실패"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "실패"
  /user/register:
    post:
      produces:
        - "application/json"
      tags:
        - "User"
      summary: "회원가입"
      parameters:
        - name: "register"
          in: "body"
          description: "register"
          schema:
            type: "string"
            properties:
              email:
                type: "string"
                example: "email@gmail.com"
              password:
                type: "string"
                example: "password"
              nickname:
                type: "string"
                example: "nickname"
      responses:
        200:
          description: "회원가입 성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "회원가입 성공"
        409:
          description: "회원가입 실패"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "이미 있는 유저"
        500:
          description: "회원가입 실패"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "회원가입 실패"
  /user/login:
    post:
      produces:
        - "application/json"
      tags:
        - "User"
      summary: "로그인"
      parameters:
        - name: "login"
          in: "body"
          description: "login"
          schema:
            type: "string"
            properties:
              username:
                type: "string"
                example: "username"
              password:
                type: "string"
                example: "password"
      responses:
        200:
          description: "로그인 성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "성공"
              access_token:
                type: "string"
                example: "accessToken"
              refresh_token:
                type: "string"
                example: "refreshToken"
        404:
          description: "로그인 실패"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "존재하지 않는 유저"
        409:
          description: "로그인 실패"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "틀린 비밀번호"
        500:
          description: "로그인 실패"
  /timeline/write:
    post:
      produces:
        - "application/json"
      consumes:
        - "multipart/form-data"
      tags:
        - "Timeline"
      summary: "타임라인 쓰기"
      parameters:
        - name: "content"
          in: "formData"
          type: "string"
          description: "내용"
        - name: "files"
          in: "formData"
          type: "array"
          items:
            type: "string"
            format: "binary"
          description: "사진 여러개"
      responses:
        200:
          description: "타임라인 작성 성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "성공"
        403:
          description: "로그인 되어있지 않음"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "로그인 되어있지 않음"
        500:
          description: "타임라인 작성 실패"
